# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
config.ssh.insert_key = false
config.vbguest.auto_update = false
config.vm.box_check_update = false
# create the (myvm) VM
config.vm.define "myvm" do |vm_config|
vm_config.vm.box = "ubuntu/bionic64"
vm_config.vm.hostname = "myvm"
vm_config.vm.network :private_network, ip: "192.168.56.10"
vm_config.vm.provider "virtualbox" do |vb|
vb.name = "myvm"
vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
vb.memory = "256"
end # of vb
# Provisioning
vm_config.vm.provision "shell", inline: 'sudo apt-get update; sudo apt-get -y install git'
end # of vm_config
end # of config